name: Main Workflow

on:
  workflow_run:
    workflows: ["Trigger Workflow"]
    types:
      - completed
    branches:
      - 'future_branch'

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  run-cpptest-make:
    name: Analyze project with C/C++test for xxx

    # Specifies the type of runner that the job will run on.
    runs-on: self-hosted

    # Specifies required permissions for upload-sarif action
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
    
    - name: Check Branch
      run: |
        if [ "${{ github.ref }}" != "refs/heads/future_branch" ]; then
          echo "This job will only run on future_branch. Skipping..."
          exit 0
        fi
      
