name: Trigger Workflow

on:
  schedule:
    - cron: '0 0 * * *' # 毎日午前0時に実行

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  trigger_job:
    runs-on: self-hosted

    # Specifies required permissions for upload-sarif action
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
    
    - name: Echo
      run: |
          echo "Trigger Finish"
